/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { NotaryServicePerformedService } from "../notaryServicePerformed.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { NotaryServicePerformedCreateInput } from "./NotaryServicePerformedCreateInput";
import { NotaryServicePerformed } from "./NotaryServicePerformed";
import { NotaryServicePerformedFindManyArgs } from "./NotaryServicePerformedFindManyArgs";
import { NotaryServicePerformedWhereUniqueInput } from "./NotaryServicePerformedWhereUniqueInput";
import { NotaryServicePerformedUpdateInput } from "./NotaryServicePerformedUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class NotaryServicePerformedControllerBase {
  constructor(
    protected readonly service: NotaryServicePerformedService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: NotaryServicePerformed })
  @nestAccessControl.UseRoles({
    resource: "NotaryServicePerformed",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createNotaryServicePerformed(
    @common.Body() data: NotaryServicePerformedCreateInput
  ): Promise<NotaryServicePerformed> {
    return await this.service.createNotaryServicePerformed({
      data: {
        ...data,

        appointment: data.appointment
          ? {
              connect: data.appointment,
            }
          : undefined,
      },
      select: {
        appointment: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        serviceCharge: true,
        serviceDescription: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [NotaryServicePerformed] })
  @ApiNestedQuery(NotaryServicePerformedFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "NotaryServicePerformed",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async notaryServicePerformeds(
    @common.Req() request: Request
  ): Promise<NotaryServicePerformed[]> {
    const args = plainToClass(
      NotaryServicePerformedFindManyArgs,
      request.query
    );
    return this.service.notaryServicePerformeds({
      ...args,
      select: {
        appointment: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        serviceCharge: true,
        serviceDescription: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: NotaryServicePerformed })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "NotaryServicePerformed",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async notaryServicePerformed(
    @common.Param() params: NotaryServicePerformedWhereUniqueInput
  ): Promise<NotaryServicePerformed | null> {
    const result = await this.service.notaryServicePerformed({
      where: params,
      select: {
        appointment: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        serviceCharge: true,
        serviceDescription: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: NotaryServicePerformed })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "NotaryServicePerformed",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateNotaryServicePerformed(
    @common.Param() params: NotaryServicePerformedWhereUniqueInput,
    @common.Body() data: NotaryServicePerformedUpdateInput
  ): Promise<NotaryServicePerformed | null> {
    try {
      return await this.service.updateNotaryServicePerformed({
        where: params,
        data: {
          ...data,

          appointment: data.appointment
            ? {
                connect: data.appointment,
              }
            : undefined,
        },
        select: {
          appointment: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          id: true,
          serviceCharge: true,
          serviceDescription: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: NotaryServicePerformed })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "NotaryServicePerformed",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteNotaryServicePerformed(
    @common.Param() params: NotaryServicePerformedWhereUniqueInput
  ): Promise<NotaryServicePerformed | null> {
    try {
      return await this.service.deleteNotaryServicePerformed({
        where: params,
        select: {
          appointment: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          id: true,
          serviceCharge: true,
          serviceDescription: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
